-- Personal Expenses table
CREATE OR REPLACE TABLE EXPENSES_DB.PUBLIC.PERSONAL_EXPENSES (
   TRAN_DATE        DATE NOT NULL,
   TRAN_DETAILS     VARCHAR(255),
   AMOUNT           DECIMAL(10,2) NOT NULL,
   CAT_ID           INT,
   PAYMENT_METHOD   VARCHAR(8)
);

-- Category Lookup table
CREATE OR REPLACE TABLE EXPENSES_DB.PUBLIC.CATEGORY_LOOKUP (
	CAT_ID          INT PRIMARY KEY,
	CAT_TYPE        VARCHAR(255),
	CAT_FILTER      BOOLEAN
);

-- Expenses Category table
CREATE OR REPLACE TABLE EXPENSES_DB.PUBLIC.EXPENSES_CATEGORY (
	EXP_NAME        VARCHAR(50),
    CAT_ID          INT
);

-- Amex Expenses table
CREATE OR REPLACE TABLE EXPENSES_DB.PUBLIC.AMEX_EXPENSES (
	DATE            VARCHAR(10),
	DESCRIPTION     VARCHAR(255),
	AMOUNT          NUMBER(38,2)
);

-- Commbank Expenses table
CREATE OR REPLACE TABLE EXPENSES_DB.PUBLIC.COMMBANK_EXPENSES (
	DATE            VARCHAR(10),
	AMOUNT          NUMBER(38,2),
	DESCRIPTION     VARCHAR(255)
);